sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.2.4 WP_MULTISITE=0
  - WP_VERSION=4.2.4 WP_MULTISITE=1
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=1

matrix:
  exclude:
    - php: 5.5
      env: WP_VERSION=3.7 WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=3.7 WP_MULTISITE=0

install: composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

before_install:
  - pip install --user codecov

after_success:
  - codecov
